### ISSUE TITLE
Deprecation error with Numpy 1.20

### ISSUE THREAD

**Issue by CoralieBy** [franpoz/SHERLOCK#82]
This error came with python3, python3.8 and the prereleases versions of SHERLOCK
[nohup.txt](https://github.com/franpoz/SHERLOCK/files/6035335/nohup.txt)

**Comment by CoralieBy** [comment]
I found that the error comes from pandas package : it still uses numpy 1.19.3 while the other packages use numpy 1.20+. The problem is that in numpy 1.20+ command lines changed, creating this deprecation error.

**Comment by martindevora** [comment]
Even though this warning should be taken into account to be fixed in the future, it is only a warning and not an error. Thus, the application continues working. We should rely here into the https://github.com/christopherburke/tess-point dependency, which seems to be the one causing the warnings and trust they will update their tool. If they don't we will reopen this in the future as the vetting will start to show failures instead of warnings.
